"""Discover page — Browse and discover new movies by genre, mood, and keywords.

Two-phase flow: first select genre tags, mood tags, and optional keyword tags,
then browse filtered movies one at a time in a card-based flow. Genres are hard
AND filters (via TMDB API), moods and keywords are soft relevance ranking (via
local keywords.db). Add to watchlist or dismiss. Rating happens on the Rate page.
"""
from __future__ import annotations

import requests
import streamlit as st
from utils.db import (
    MOOD_CATEGORY_ORDER,
    classify_movie_keywords,
    get_movie_keywords_from_index,
    get_popular_keywords,
    keywords_db_available,
    load_mood_categories,
    save_dismissed,
    save_to_watchlist,
    score_movies_by_keywords,
    search_keywords,
)
from utils.tmdb import (
    discover_movies,
    get_genre_map,
    get_movie_details,
    get_trending,
    poster_url,
)

# Provider brand colors for streaming badges (same mapping as Watchlist page)
_PROVIDER_COLORS: dict[str, str] = {
    "Netflix": "red",
    "Amazon Prime Video": "blue",
    "Disney Plus": "green",
    "Apple TV Plus": "gray",
    "Paramount Plus": "orange",
}
_DEFAULT_PROVIDER_COLOR = "violet"

# Header changes based on phase: genre selection vs. movie browsing
if st.session_state.get("discover_phase", "select") == "select":
    st.header("Which movie will you watch?", divider="gray", text_alignment="center")
else:
    st.header("Discover movies", divider="gray")

# --- Deferred toast ---
if "_discover_toast" in st.session_state:
    _toast_msg, _toast_icon = st.session_state.pop("_discover_toast")
    st.toast(_toast_msg, icon=_toast_icon)

# --- Load genre data for tag selection ---
# Genre map is needed for pills UI and resolving genre IDs on movie cards.
try:
    genre_map = get_genre_map()
except requests.HTTPError as e:
    if e.response is not None and e.response.status_code == 401:
        st.error(
            "Invalid TMDB API key. Check `.streamlit/secrets.toml`.",
            icon=":material/key_off:",
        )
    else:
        st.error("TMDB API error. Please try again later.", icon=":material/error:")
    st.stop()
except requests.ConnectionError:
    st.error(
        "Could not connect to TMDB. Check your internet connection.",
        icon=":material/wifi_off:",
    )
    st.stop()

# --- Load keyword + mood data for tag selection ---
# Keywords come from the pre-populated keywords.db (read-only, no API calls).
# Mood categories come from the keyword_moods table (generated by mood_classify.py).
_keyword_name_to_id: dict[str, int] = {}
_keyword_options: list[str] = []
_mood_categories: dict[str, list[int]] = {}  # category name → keyword IDs
if keywords_db_available():
    _popular_keywords = get_popular_keywords(limit=30)
    _keyword_name_to_id = {kw["keyword_name"]: kw["keyword_id"] for kw in _popular_keywords}
    _keyword_options = [kw["keyword_name"] for kw in _popular_keywords]
    # Load mood categories from keyword_moods table (10 categories, 33k keywords)
    _mood_categories = load_mood_categories()

# --- Extra keywords added via search popover ---
# Persists across reruns so searched keywords stay visible as pills.
st.session_state.setdefault("_discover_extra_keywords", {})  # name → id
# Process pending keyword addition from the search popover callback
if "_discover_add_keyword" in st.session_state:
    _name, _kid = st.session_state.pop("_discover_add_keyword")
    st.session_state._discover_extra_keywords[_name] = _kid
    # Pre-select the newly added keyword in the pills widget
    _current_sel = list(st.session_state.get("keyword_pills", []))
    if _name not in _current_sel:
        _current_sel.append(_name)
    st.session_state.keyword_pills = _current_sel
# Merge extra keywords into the options list (after popular, no duplicates)
for _name, _kid in st.session_state._discover_extra_keywords.items():
    if _name not in _keyword_name_to_id:
        _keyword_name_to_id[_name] = _kid
        _keyword_options.append(_name)

# --- Phase management ---
# Two phases: "select" (genre + keyword tags) → "browse" (movie cards)
st.session_state.setdefault("discover_phase", "select")
st.session_state.setdefault("discover_index", 0)


def _start_browsing() -> None:
    """Transition from genre/mood/keyword selection to movie browsing."""
    # Save filter names for display on browse phase and restoration on back
    selected = list(st.session_state.get("genre_pills", []))
    st.session_state["_discover_saved_genres"] = selected
    st.session_state["_discover_saved_moods"] = list(
        st.session_state.get("mood_pills", []),
    )
    st.session_state["_discover_saved_keywords"] = list(
        st.session_state.get("keyword_pills", []),
    )
    # Reverse-lookup: resolve genre names back to TMDB genre IDs for the API call
    st.session_state["_discover_genres"] = tuple(sorted(
        gid for gid, name in genre_map.items() if name in (selected or [])
    ))
    # Collect keyword IDs from both mood and keyword pills for unified scoring
    all_keyword_ids: list[int] = []
    # Mood pills → expand each category to all its keyword IDs
    selected_mood_cats = st.session_state.get("mood_pills", [])
    if selected_mood_cats and _mood_categories:
        for cat_name in selected_mood_cats:
            if cat_name in _mood_categories:
                all_keyword_ids.extend(_mood_categories[cat_name])
    # Keyword pills → individual keyword IDs
    selected_kw_names = st.session_state.get("keyword_pills", [])
    if selected_kw_names and _keyword_name_to_id:
        all_keyword_ids.extend(
            _keyword_name_to_id[name]
            for name in selected_kw_names
            if name in _keyword_name_to_id
        )
    st.session_state["_discover_keywords"] = tuple(all_keyword_ids)
    # Switch to browse phase and reset movie position to the first result
    st.session_state.discover_phase = "browse"
    st.session_state.discover_index = 0


def _back_to_selection() -> None:
    """Return to genre/keyword selection phase, preserving filter state."""
    st.session_state.discover_phase = "select"
    # Restore pills widget state from saved selections so filters are not lost
    if "_discover_saved_genres" in st.session_state:
        st.session_state["genre_pills"] = st.session_state["_discover_saved_genres"]
    if "_discover_saved_moods" in st.session_state:
        st.session_state["mood_pills"] = st.session_state["_discover_saved_moods"]
    if "_discover_saved_keywords" in st.session_state:
        st.session_state["keyword_pills"] = st.session_state["_discover_saved_keywords"]


# === PHASE 1: Genre + Keyword Selection ===
if st.session_state.discover_phase == "select":
    # Genre pills — hard AND filter via TMDB API
    st.subheader("Genre")
    selected_genres = st.pills(
        "Genre",
        options=list(genre_map.values()),
        selection_mode="multi",
        key="genre_pills",
        label_visibility="collapsed",
    )

    # Mood pills — 10 mood categories, each expanding to thousands of keyword IDs
    selected_moods: list[str] = []
    if _mood_categories:
        st.subheader("Mood")
        selected_moods = st.pills(
            "Mood",
            options=MOOD_CATEGORY_ORDER,
            selection_mode="multi",
            key="mood_pills",
            label_visibility="collapsed",
        )

    # Keyword pills — soft relevance ranking via keywords.db (only shown if DB exists)
    selected_keywords: list[str] = []
    if _keyword_options or keywords_db_available():
        st.subheader("Keywords")
        if _keyword_options:
            selected_keywords = st.pills(
                "Keywords",
                options=_keyword_options,
                selection_mode="multi",
                key="keyword_pills",
                label_visibility="collapsed",
            )
        # Search popover — find any keyword from the full ~34k keyword index
        with st.popover(":material/search: Find keyword"):
            _kw_query = st.text_input(
                "Search keywords",
                placeholder="e.g. based on novel, time travel...",
                key="_discover_kw_search",
                icon=":material/search:",
                label_visibility="collapsed",
            )
            if _kw_query and len(_kw_query) >= 2:
                _results = search_keywords(_kw_query, limit=10)
                # Exclude keywords already shown in the pills
                _results = [r for r in _results if r["keyword_name"] not in _keyword_name_to_id]
                if _results:
                    for _r in _results:
                        if st.button(
                            _r["keyword_name"],
                            key=f"kw_add_{_r['keyword_id']}",
                            icon=":material/add:",
                            use_container_width=True,
                        ):
                            # Store pending addition — processed on next rerun
                            st.session_state["_discover_add_keyword"] = (
                                _r["keyword_name"], _r["keyword_id"],
                            )
                            st.rerun()
                else:
                    st.caption("No keywords found.")

    # Button label adapts: "Search" with any selection, "Show trending" without
    has_selection = selected_genres or selected_moods or selected_keywords
    st.button(
        "Search" if has_selection else "Show trending",
        icon=":material/search:",
        on_click=_start_browsing,
        type="primary",
    )
    st.stop()  # Halt rendering — only selection UI is shown in this phase

# === PHASE 2: Movie Browsing ===
# Retrieve genre IDs and keyword IDs stored by _start_browsing callback
selected_ids = st.session_state.get("_discover_genres", ())
selected_keyword_ids = st.session_state.get("_discover_keywords", ())

# Back button to return to genre/keyword selection
st.button("Change filters", icon=":material/arrow_back:", on_click=_back_to_selection)

# --- Active filter badges ---
# Show currently selected genres, moods, and keywords as inline badges
_active_genres = st.session_state.get("_discover_saved_genres", [])
_active_moods = st.session_state.get("_discover_saved_moods", [])
_active_keywords = st.session_state.get("_discover_saved_keywords", [])
if _active_genres or _active_moods or _active_keywords:
    _filter_parts: list[str] = []
    _filter_parts.extend(f":gray-badge[{g}]" for g in _active_genres)
    _filter_parts.extend(f":primary-badge[{m}]" for m in _active_moods)
    _filter_parts.extend(f":gray-badge[{k}]" for k in _active_keywords)
    st.markdown(" ".join(_filter_parts))

# --- Load movies with automatic pagination ---
# When keywords are active, pre-fetch more pages to build a ranking pool.
# Without keywords, stop as soon as any available movie is found.
dismissed = st.session_state.dismissed
watchlisted_ids = {m["id"] for m in st.session_state.watchlist}
rated_ids = st.session_state.ratings  # dict {movie_id: rating} — membership check is O(1)
available: list[dict] = []  # Accumulates unseen movies across pages
# 5 pages (~100 movies) gives enough pool for meaningful keyword ranking
_TARGET_POOL = 100 if selected_keyword_ids else 1

try:
    for page in range(1, 11):
        if selected_ids:
            movies = discover_movies(selected_ids, page=page)
        else:
            movies = get_trending(page=page)

        if not movies:
            break  # No more results from API

        # Filter out dismissed, watchlisted, and already-rated movies
        available.extend(
            m for m in movies
            if m["id"] not in dismissed
            and m["id"] not in watchlisted_ids
            and m["id"] not in rated_ids
        )

        # Without keywords: stop at first available movie
        # With keywords: collect enough movies for ranking
        if available and len(available) >= _TARGET_POOL:
            break
except requests.HTTPError as e:
    if e.response is not None and e.response.status_code == 401:
        st.error(
            "Invalid TMDB API key. Check `.streamlit/secrets.toml`.",
            icon=":material/key_off:",
        )
    else:
        st.error("TMDB API error. Please try again later.", icon=":material/error:")
    st.stop()
except requests.ConnectionError:
    st.error(
        "Could not connect to TMDB. Check your internet connection.",
        icon=":material/wifi_off:",
    )
    st.stop()

# --- Keyword scoring & filtering ---
# Score movies by how many selected keywords they match, then sort by
# score (descending) with TMDB popularity as tiebreaker. Hard-filter:
# only keep movies that actually match at least one selected keyword,
# so unrelated movies (score 0) are never shown.
if selected_keyword_ids and available:
    scores = score_movies_by_keywords(
        [m["id"] for m in available],
        list(selected_keyword_ids),
    )
    available = [m for m in available if scores.get(m["id"], 0) > 0]
    available.sort(key=lambda m: (-scores.get(m["id"], 0), -m.get("popularity", 0)))

if not available:
    if selected_ids:
        st.info(
            "No movies found for these genres. Try selecting fewer tags!",
            icon=":material/search_off:",
        )
    else:
        st.info(
            "You have seen all trending movies! Check back later for new ones.",
            icon=":material/celebration:",
        )
    st.stop()

# --- Current movie card ---
# Modulo wraps the index to stay within bounds when the list shrinks
index = st.session_state.discover_index % len(available)
movie = available[index]

# Fetch full details for runtime and streaming providers (cached 1h)
_movie_details: dict | None = None
try:
    _movie_details = get_movie_details(movie["id"])
except requests.RequestException:
    pass  # Non-critical — card still works with basic data

# Resolve genre IDs to human-readable names
genre_names = [genre_map.get(gid, "Unknown") for gid in movie.get("genre_ids", [])]

# Look up all keywords from the keyword index (no API call, always shown)
movie_keywords = get_movie_keywords_from_index(movie["id"])
# Split into mood categories and regular keywords via ML classification
mood_cats, regular_kws = classify_movie_keywords(movie_keywords)

# Card layout: poster on the left, info on the right
with st.container(border=True):
    col_poster, col_info = st.columns([1, 2])
    with col_poster:
        # w342 poster size for card display
        st.image(poster_url(movie.get("poster_path")), width=250)
    with col_info:
        st.subheader(movie["title"])
        # Genre section
        if genre_names:
            st.caption("**Genre**")
            st.markdown(" ".join(f":gray-badge[{g}]" for g in genre_names))
        # Mood section — category names as primary badges (Cinema Gold)
        if mood_cats:
            st.caption("**Mood**")
            st.markdown(" ".join(
                f":primary-badge[{cat}]" for cat in mood_cats
            ))
        # Keywords section — unclassified keywords as gray badges
        if regular_kws:
            st.caption("**Keywords**")
            st.markdown(" ".join(
                f":gray-badge[{kw['keyword_name']}]" for kw in regular_kws
            ))
        # TMDB rating — 1 decimal for consistent display
        _tmdb = movie.get("vote_average")
        st.caption(f"TMDB rating: {_tmdb:.1f} / 10" if _tmdb else "TMDB rating: N/A")
        # Runtime (from details API, not available in discover/trending responses)
        if _movie_details:
            _runtime = _movie_details.get("runtime")
            if _runtime:
                _h, _m = divmod(_runtime, 60)
                st.caption(f":material/schedule: {_h}h {_m}min" if _h else f":material/schedule: {_m} min")
        st.write(movie.get("overview", "No description available."))
    # Streaming providers for Switzerland (from details API)
    if _movie_details:
        _providers = _movie_details.get("watch/providers", {}).get("results", {}).get("CH", {})
        _flatrate = _providers.get("flatrate", [])
        if _flatrate:
            st.markdown("**Streaming in Switzerland:** " + " ".join(
                f":{_PROVIDER_COLORS.get(p['provider_name'], _DEFAULT_PROVIDER_COLOR)}-badge[{p['provider_name']}]"
                for p in _flatrate
            ))

# --- Action buttons ---
# Watchlist and dismiss are separate actions that advance to the next movie.


def _add_to_watchlist() -> None:
    """Add current movie to watchlist and advance to next."""
    st.session_state.watchlist.append(movie)  # Update runtime state
    save_to_watchlist(movie)  # Persist full movie dict to SQLite
    st.session_state.discover_index += 1  # Advance to next movie on rerun
    st.session_state["_discover_toast"] = (
        f"Added **{movie['title']}** to watchlist", ":material/bookmark:",
    )


def _dismiss() -> None:
    """Mark current movie as dismissed and advance to next."""
    st.session_state.dismissed.add(movie["id"])  # Update runtime set
    save_dismissed(movie["id"])  # Persist dismissal to SQLite
    st.session_state.discover_index += 1  # Advance to next movie on rerun
    st.session_state["_discover_toast"] = (
        f"Skipped **{movie['title']}**", ":material/thumb_down:",
    )


with st.container(horizontal=True):
    st.button("Not interested", icon=":material/thumb_down:", on_click=_dismiss)
    st.button(
        "Add to watchlist", icon=":material/bookmark:",
        on_click=_add_to_watchlist, type="primary",
    )

# Movie counter — shows position within available results
st.caption(f"Movie {index + 1} of {len(available)}", text_alignment="center")

